import React from 'react'

export const Home: React.FC = () => {
  return (
    <div className="p-10 items-start">
      <h1 className="text-2xl">Redux + TypeScript</h1>
      <p>
        Hello and welcome! :) This app was generated by the Create React App
        template and bootstrapped with Redux, React Router, TypeScript, ESlint,
        Prettier, Craco and Tailwind for you.
      </p>
    </div>
  )
}
