import React, { Fragment } from 'react'
import Counter from '../components/Counter'

export const Home: React.FC = () => {
  return (
    <Fragment>
      <h1 className="text-lg">Redux + TypeScript</h1>
      <p>
        Hello and welcome! :) This app was generated by the Create React App
        template and bootstrapped with Redux, React Router, TypeScript, ESlint,
        Prettier, Craco and Tailwind for you.
      </p>
      <Counter />
    </Fragment>
  )
}
